%% -*- erlang -*-
-ifndef(DUI_REDIS_HRL).
-define(DUI_REDIS_HRL, true).

%% Application version (also mirrored in dui_redis.erl).
-define(DUI_REDIS_VERSION, "0.1.0").

%% Root component state. All screens share this single state, mirroring
%% redis-tui's Model.
-record(dui_state, {
    runtime :: pid() | undefined,
    cli = #{} :: map(),
    config_path :: string() | undefined,
    screen = connections :: atom(),
    prev_screen :: atom() | undefined,
    size = {24, 80} :: {pos_integer(), pos_integer()},
    connections = [] :: [map()],
    selected = 0 :: non_neg_integer(),
    current_conn :: map() | undefined,
    editing_conn :: map() | undefined,
    conn_form = #{} :: map(),
    confirm :: term() | undefined,
    test_result :: binary() | undefined,
    connection_error :: binary() | undefined,
    connected = false :: boolean(),
    keys = [] :: [map()],
    selected_key = 0 :: non_neg_integer(),
    key_cursor = 0 :: non_neg_integer(),
    key_pattern = <<"*">> :: binary(),
    total_keys = 0 :: integer(),
    sort_by = key :: key | type | ttl,
    sort_asc = true :: boolean(),
    filter_active = false :: boolean(),
    filter_edit :: term() | undefined,
    search_seq = 0 :: integer(),
    preview_key = <<>> :: binary(),
    preview_value :: map() | undefined,
    loading_keys = false :: boolean(),
    db_input :: term() | undefined,
    current_key :: map() | undefined,
    current_value :: map() | undefined,
    detail_scroll = 0 :: non_neg_integer(),
    editor :: term() | undefined,
    prompt :: term() | undefined,
    prompt_purpose :: term() | undefined,
    history :: term() | undefined,
    results = [] :: [map()],
    selected_result = 0 :: non_neg_integer(),
    results_title = <<>> :: binary(),
    results_purpose = undefined :: atom() | undefined,
    tree_nodes = [] :: [map()],
    tree_expanded = [] :: [binary()],
    selected_tree = 0 :: non_neg_integer(),
    result_text :: binary() | undefined,
    server_info :: map() | undefined,
    slow_log = [] :: [map()],
    clients = [] :: [map()],
    memory_stats :: map() | undefined,
    metrics = [] :: [map()],
    metrics_active = false :: boolean(),
    expiring = [] :: [map()],
    row_selected = 0 :: non_neg_integer(),
    channels = [] :: [binary()],
    sub :: pid() | undefined,
    sub_target = <<>> :: binary(),
    sub_kind = channel :: channel | pattern,
    sub_messages = [] :: [map()],
    sub_scroll = 0 :: non_neg_integer(),
    sub_follow = true :: boolean(),
    config_params = [] :: [{binary(), binary()}],
    cluster_nodes = [] :: [map()],
    cluster :: map() | undefined,
    groups = [] :: [map()],
    status :: {info | error, binary()} | undefined,
    status_tick = 0 :: non_neg_integer(),
    loading = false :: boolean(),
    show_help = false :: boolean(),
    ticks = 0 :: non_neg_integer()
}).

-endif.
